### ISSUE TITLE
hardcoded CP url

### ISSUE THREAD

**Issue by alexanderhofstaetter** [4rn0/statamic-v2-image-optimizer#12]
in fieldtype.js there is on multiple lines a hardcoded URL from the CP.

`var url = '/cp/addons/image-optimizer/optimize';`

For me this does not work because I have a custom CP route in index.php defined.

Additionally if I have a default language != 'en' all the strings does not get loaded. only when I rename the dir lang/en to lang/de

**Comment by 4rn0** [comment]
I comitted a fix in master. Please let me know if it works out for you and I will tag a new release.

**Comment by alexanderhofstaetter** [comment]
I will check yes, can you fix the language problem too?

I think you need to configure the en locale as fallback because I only have the 'de' locale defined.

![image](https://user-images.githubusercontent.com/6820505/52373774-ce1e6600-2a5b-11e9-9d95-0217525f3f97.png)

**Comment by 4rn0** [comment]
I'm not sure how to do that. The docs don't mention a fallback language: https://docs.statamic.com/addons/classes/settings#ui

You're welcome to add a German translation if you'd like!
