### ISSUE TITLE
Image fails to generate

### ISSUE THREAD

**Issue by vitor-ao** [4rn0/statamic-v2-image-optimizer#3]
After installing the addon, every image generated with [Glide Tag](https://docs.statamic.com/tags/glide) returns the following error:
`LOG.error: getimagesize(): Filename cannot be empty`

Un-optimized images are generated but not displayed (they returns an empty src).

Th same happens on the thumbnails of the assets on the Control Panel. Searching the CP logs, I found the error:
`dev.ERROR: ErrorException: getimagesize(): Filename cannot be empty in K:\xampp\htdocs\new-website\statamic\vendor\ps\image-optimizer\src\ImageOptimizer\TypeGuesser\GdTypeGuesser.php:18`

**Comment by monstromatic** [comment]
I have the same issue

**Comment by madsem** [comment]
me three, also no image optimization took place at all.
fyi: I have only custom asset containers, removed the default one. maybe that is the problem

**Comment by 4rn0** [comment]
I believe I found an issue with custom asset container. It will be fixed in an upcoming 2.0 release. Thanks for reporting it guys!
