### ISSUE TITLE
2.0.7 discussion

### ISSUE THREAD

**Issue by madsem** [4rn0/statamic-v2-image-optimizer#9]
Just installed it, it's def. cleaner that way, I like it :)

But couldn't even get past the first `php please optimize`
error:
```bash
vagrant@homestead:~/code/fresh-statamic$ php please optimize
Your Glide image cache is now so very, very empty.
  1/17 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   5%
                                 
  [ErrorException]               
  filesize(): stat failed for 1  
```

Because you're checking the wrong file `if ($tempfile && filesize($tempfile))` on line 194.
You need to check if the actual temporary file exists, and if the variable is set.
`if ($tempfile && isset($temp) && filesize($temp))`

Everything else looks great :) Will run once more on a fresh install, and then I believe this can be released?

**Comment by 4rn0** [comment]
Thanks for catching that! Fixed it right away!

**Comment by madsem** [comment]
There is also another bug for default settings I just found.
```bash
[2019-01-14 10:40:31] production.INFO: Starting optimization: /usr/bin/pngquant --force --output='/home/vagrant/code/fresh-statamic/assets/img/Screen Shot 2019-01-11 at 3.19.46 PM.png'  
[2019-01-14 10:40:31] production.ERROR: No input files specified.
```

**Comment by madsem** [comment]
`ImageOptimizer.php` line 39 should be `--force :file --output=:file`

**Comment by 4rn0** [comment]
Fixed that too! :-)

**Comment by madsem** [comment]
Cool, I believe we're done here 💃 
And we got the best out of the addon

**Comment by 4rn0** [comment]
Awesome! Thanks so much for pitching in. I will merge this branch to master and tag a new release!

**Comment by madsem** [comment]
It's been a pleasure :)
